### ISSUE TITLE
US: GRCh38 coordinate search

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#10]
As a biologist, I can call up graph displays given a genomic coordinate on the GRCh38 reference, so that I can find the parts of the genome I study.

**Comment by cmarkello** [comment]
@adamnovak This is something that still confuses me. Wouldn't this require some kind of surjection of graph node id's to GRCh38 coordinate space? If not, why then is the `vg surject` function required to 'lift-over'/convert a .gam into a .bam file?

**Comment by ekg** [comment]
This is provided by the xg index. vg find has a way to find genomics
positions in the graph using embedded positional paths.

**Comment by cmarkello** [comment]
Is this how vg surject works?

**Comment by ekg** [comment]
Surjection takes alignments, gets the subgraph they map to, removes
everything but a given positional path, and then realigns the read to that
subgraph. The result is equivalent to an alignment to the linear reference
and can be written out in BAM.

This is not really the same thing Adam is talking about.

**Comment by adamnovak** [comment]
They're sort of opposites. Surject takes graph space and tries to figure
out where in linear space it is. This idea is taking linear space and
finding where it is in graph space, which is an easier problem.

**Comment by adamnovak** [comment]
We can do this with embedded named paths.
