### ISSUE TITLE
Network error with Demo

### ISSUE THREAD

**Issue by brettChapman** [vgteam/sequenceTubeMap#101]
Hi

I'm attempting to access https://vgteam.github.io/sequenceTubeMap/

However the demo examples are now not loading and give error: Network error fetching data

I like to use the demo to upload custom files to test my constructed graphs, however it also doesn't let me upload either. Thanks.

**Comment by brettChapman** [comment]
I noticed some recent commits. Perhaps they've caused issues with the live demo?

I also had issues with my local install if I installed the latest version of sequenceTubeMap, but after installing VG 1.2.1 and rolling back sequenceTubeMap to the last commit (hash cb66fc59a9ddc3cb54847732be4daf7264f39abc) the issue seemed to resolve itself. I was getting the following error when using the latest build on master:

```
vagrant@vagrant:~/sequenceTubeMap$ npm run serve

> sequence-tube-maps@0.1.0 serve /home/vagrant/sequenceTubeMap
> node ./src/server.js

TubeMapServer listening on port 3000!
received request for filenames
{ xgFiles: [ 'cactus.vg.xg', 'snp1kg-BRCA1.vg.xg', 'x.vg.xg' ],
  gbwtFiles: [ 'x.vg.gbwt' ],
  gamIndices: [ 'NA12878-BRCA1.sorted.gam', 'cactus-NA12879.sorted.gam' ] }
http POST chr22_v4 received
nodeID = 1
distance = 100
no gbwt file provided.
dataPath = ./exampleData/
(node:15746) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
vg chunk exited with code 0
vg view exited with code 0
vg chunk: 50.513ms
annotationFile: ./tmp-837f6f60-3853-11eb-95a8-c19cb3949dfd/chunk_0_17_0_603.annotate.txt
processing annotation file: 3.152ms
processing gam file: 46.627ms
processing region file: 1.744ms
request-duration: 125.629ms
```

**Comment by brettChapman** [comment]
Besides those warning, the screen goes blank when I go to the URL, so it was unusable unless I rolled back to a previous commit.

**Comment by dortaelliott** [comment]
Hello Bret, you have been able to solve the problem, I have the same and I have not been able to solve it, if you have found the solution you would mind posting it. Thanks

**Comment by brettChapman** [comment]
Hi @dortaelliott

I resorted to setting up my own sequenceTubeMap instance on a server. I found I needed to role back the version though for VG to work with sequenceTubeMap. I'm running VG version 1.21 and ran the following to get a version of sequenceTubeMap which didn't error out. Any graphs you want to display, just reindex them using VG version 1.21 and they'll work. I set this up some time ago, so I don't know if any issues have been resolved in later versions now.

```
git clone https://github.com/vgteam/sequenceTubeMap.git
cd sequenceTubeMap/
git reset --hard cb66fc59a9ddc3cb54847732be4daf7264f39abc
git checkout cb66fc59a9ddc3cb54847732be4daf7264f39abc
```

**Comment by matt-shenton** [comment]
It seems like, as you say, the latest sequenceTubeMap and vg don't work together. Unfortunately, I can only get the latest vg to install on my macbook pro.

indexing with vg 1.21 on a linux machine works, but the local vg is still required I think, so I guess I have to patiently wait for sequenceTubeMap to get updated. Thanks for posting your insights.

**Comment by dortaelliott** [comment]
I have proceeded to follow the installation guide, I have downloaded version 1.21, I have added it to the path as indicated, later once cloando the repository I have made vg index x.vg -x x.xv.xg and so on with the three files and it still doesn't work for me, can you tell me if I'm doing something wrong?

Thanks a lot.

**Comment by brettChapman** [comment]
@dortaelliott 

Have you put vg 1.21 in /vg/bin ?

You also need to cd into sequenceTubeMap before running npm run serve.

I had issues installing npm due to missing packages. I needed to install like this:
```
npm install
npm audit fix
npm run build
```

You also need to be running on a server with an open port to the default port sequenceTubeMap uses: i.e. 3000.

I first tested sequenceTubeMap in vagrant on my MacBook Pro instead of my ubuntu server. I installed vagrant through homebrew. https://sourabhbajaj.com/mac-setup/Vagrant/README.html

Like you, I also reindexed the vg graphs in the exampleData

**Comment by adamnovak** [comment]
This issue is tracking several issues.

We caught the network error with the demo and resolved it by rebooting the stuck backend server, so that's fixed now.

The problem with the latest commit not working was I think introduced [when we decided to start unconditionally dropping the first character of nodeName here](https://github.com/vgteam/sequenceTubeMap/pull/94/files#diff-d02755cbc095a81f0817f9694c6e0a59dc3794a3b7a34cf5c3fd7cb4eda283c3R962). That isn't going to work. I've opened #103 to track that.

The currently committed xg indexes are stale and need to be rebuilt. I've opened #104 to track that.

Finally, I've opened #105 to track the need for an npm install workaround.

The underlying cause of a lot of these issues is a lack of CI; I have opened #106 to track that.

I'm going to close this issue out, as the network error originally reported is solved. You are welcome to keep chatting here, or in https://www.biostars.org/t/vg/
