### ISSUE TITLE
Revise insertion display

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#14]
Insert character should be a vertical line.

You should be able to mouse over it and see the inserted sequence and where it fits in the node's sequence (with an extended vertical line to the top).

**Comment by wolfib** [comment]
Insertions are now marked with an asterisk. A vertical line is quite similar to a 'T', especially when the horizontal part is close to where one color ends and the next one begins.

The vertical line extending to the top has been implemented.
