### ISSUE TITLE
Graph coordinates 

### ISSUE THREAD

**Issue by SimonaSecomandi** [vgteam/sequenceTubeMap#141]
Dear all,

I'm using Sequence Tube Map to visualize my vg graph (generated with the Cactus Pangenome Pipeline). 

In particular, I want to visualize a gene that goes from 17272192 to 17276215 (length 4023 bp) on the chromosome 10 of the fasta file reference genome I used in the graph.

On the website (opened using yarn serve) I've selected the chromosome 10 path and then I set the start as 17272192  and then length as 4023 to visualize the entire sequence. Is that ok? Are the coordinates the same as the fasta file I used?

Many thanks!

**Comment by SimonaSecomandi** [comment]
Dear all, I'm still wondering if the coordinates in Sequence Tube Map are the same as my fasta file.

Many thanks!

**Comment by adamnovak** [comment]
The coordinates on the path should be the same as the coordinates in the FASTA that defines the sequence that the path represents.

**Comment by adamnovak** [comment]
I'm going to close this; I think we answered the question here.
