### ISSUE TITLE
Form fields are weirdly wide now

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#149]
As noted in https://github.com/vgteam/sequenceTubeMap/pull/147#issuecomment-1054591489, currently our form fields for selecting what to draw are much wider than they seem to need to be, and it makes our header take up a lot more space than it really should.

We should make them narrower so our header can be one or two rows on desktop screen sizes.

**Comment by nojronatron** [comment]
Thanks for labeling 'good-first-issue'. 😄  I took at stab at shoring up the overflow issue in the Header in [PR 173](https://github.com/vgteam/sequenceTubeMap/pull/173), included screenshots.

**Comment by adamnovak** [comment]
I think this is fixed now.
