### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#189]
I noticed today that packages somewhere in our dependency tree have released security updates, and NPM complains that we have old versions in the tree when we `npm install`.

Somebody should fix that.

**Comment by zt4ff** [comment]
Hi @adamnovak 
what if we include a Git actions workflow that creates a new pull request updating `package.json` to update packages and securities issues using Depandabot?

I would like to work on this issue

**Comment by adamnovak** [comment]
This was fixed in #201
