### ISSUE TITLE
Eliding small snarls

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#196]
@benedictpaten has the idea that maybe we could have a way to remove small snarls (e.g. single base indels and SNPs) from the tube map, to get a more legible higher-level zoomed-out view.

This might involve having and then modifying the snarl structure of the graph, and might require support on the `vg` side.

**Comment by colindaven** [comment]
Excluding small SNPs and indels would be something which we'd love to see as well. Most users seem to be interested in larger features, especially insertions (eg 100 bp + ). The SNPs get in the way a lot.

If there was an easy workaround with vg/odgi to preprocess data it would be fine too, but I'm not aware of how to do this.

**Comment by adamnovak** [comment]
You can use `vg simplify` to remove small variants (AKA small "snarls") from a graph. But it won't also process aligned reads.

**Comment by colindaven** [comment]
Thanks, that's very useful info.

**Comment by benedictpaten** [comment]
I do think this is an issue we should revisit in tubemaps, along with
having indexed support for the GBZ.

**Comment by adamnovak** [comment]
To start on this, we would need:
* A flag in the API request asking the server to do this
* A pass on the server side where we run `vg simplify`, or else new functionality in `vg chunk` behind its own flag (which could also rewrite the reads)
* A checkbox on the client side to control this (probably in the graph track settings)
* Some kind of interlock to keep read tracks from being used with a simplified graph track unless they can be rewritten

**Comment by adamnovak** [comment]
Before adding a new server-side optional pass, we might want to refactor the existing server logic to async/await instead of each phase just calling the next one.

**Comment by adamnovak** [comment]
The server [makes a call to vg chunk](https://github.com/vgteam/sequenceTubeMap/blob/0280401b5ab6da396231a06a2c9b3f6d6596418b/src/server.mjs#L429C11-L429C22) to extract the part of the graph to look at, and then it [makes a call to vg view](https://github.com/vgteam/sequenceTubeMap/blob/0280401b5ab6da396231a06a2c9b3f6d6596418b/src/server.mjs#L430) to convert the graph to JSON, and it [pipes the output of vg chunk into vg view](https://github.com/vgteam/sequenceTubeMap/blob/0280401b5ab6da396231a06a2c9b3f6d6596418b/src/server.mjs#L455-L457).

We want to interpose a call to `vg simplify`.

**Comment by adamnovak** [comment]
`vg simplify`'s help documentation:
```
[anovak@swords ~]% vg simplify --help
usage: vg simplify [options] old.vg >new.vg
general options:
    -a, --algorithm NAME   simplify using the given algorithm (small, rare; default: small)
    -t, --threads N        use N threads to construct graph (defaults to numCPUs)
    -p, --progress         show progress
    -b, --bed-in           read in the given BED file in the cordinates of the original paths
    -B, --bed-out          output transformed features in the coordinates of the new paths
small snarl simplifier options:
    -m, --min-size N       remove leaf sites with fewer than N bases involved (default: 10)
    -i, --max-iterations N perform up to N iterations of simplification (default: 10)
rare variant simplifier options:
    -v, --vcf FILE         use the given VCF file to determine variant frequency (required)
    -f, --min-freq FLOAT   remove variants with total alt frequency under FLOAT (default: 0)
    -c, --min-count N      remove variants with total alt occurrence count under N (default: 0)
```

**Comment by adamnovak** [comment]
The input filename can be `-` to read from standard input.

**Comment by adamnovak** [comment]
To send the new flag to the server, we have to add it to the result of `getNextViewTarget()`: https://github.com/vgteam/sequenceTubeMap/blob/ede0f70ee89249ffa26f64c949deb62af8ec348f/src/components/HeaderForm.js#L462-L468

**Comment by adamnovak** [comment]
We'd have to fill it in either from a new state field in HeaderForm, or a new state field above HeaderForm (that could then get bound down into the customization accordion), or from a field inside the `tracks` state that already exists in HeaderForm (so we could control it from the graph tracks settings).

Or we could just put it in the graph track and not have a separate flag for it, and we could make the server look inside the graph track to see if it should be simplified or not.

**Comment by adamnovak** [comment]
Checkbox button examples for controlling `simplify`: https://reactstrap.github.io/?path=/docs/components-buttongroup--checkbox-and-radio

**Comment by adamnovak** [comment]
Until we can also adjust the reads when simplifying (via a new `vg simplify` feature?) we need to make sure the user can't use simplification and read tracks at the same time.

We also shouldn't let the user use it with a BED region selected.

**Comment by adamnovak** [comment]
Rather than forbidding simplification with BED regions, we can just add the simplify pass in front of the vg view pass when reading the chunk's graph, as long as no read tracks are in use.
