### ISSUE TITLE
US: Display reads, reference, and haplotypes

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#2]
As a genomicist, I can display sequencing reads in the context of both the primary reference and local unique haplotypes simultaneously, so that I can see how well my reads fit with both.

**Comment by wolfib** [comment]
Currently the display does not discern between vg reference paths and xg haplotype threads. They are both part of the same visualisation and look alike. The only way to tell them apart is via the labels in the legend. If there is no objection, I'd like to keep it that way.

**Comment by adamnovak** [comment]
They really should be basically the same class of object. But we might want
to be able to distinguish them (or maybe just the primary path?) by color,
and we will want the user to be able to tell which category a particular
path/thread is if they want to know.
