### ISSUE TITLE
D3.js Version

### ISSUE THREAD

**Issue by subwaystation** [vgteam/sequenceTubeMap#25]
Hi Wolfgang ;)

I hope you had a smooth transition into the new year :)

I was wondering if there is any particular reason, why you are still using D3.js V3 instead of V4?

Best,
Simon

**Comment by wolfib** [comment]
Hi Simon,

Happy new year to you too!

No, there's no particular reason why D3.js version 3 is being used instead of version 4. It's simply the version which was around when I started the project.

V4 introduces breaking changes afaik, so I didn't really bother upgrading. What would the advantages be?

**Comment by subwaystation** [comment]
I have to admit that on the short run there only are disadvantages:

- So far V3 still works, so why touch a running system?
- Porting could be very time intensive, because there are a lot of changes breaking code which was written in V4 (see https://github.com/d3/d3/blob/master/CHANGES.md for a full change log). However, from my experience when porting part of your implementation during my master thesis to V4, it was surprisingly straightforward (when I was into your code ~1 day).
- One would have to inform oneself about the changes from V3 to V4 in order to produce valid V4 code.

On the long run I see the following advantages:

- The newly introduced modularity of D3 should lower implementation efforts.
- The D3 modules are always up to date:
  - All bugfixes are available
  - Access to the latest features (though, it remains discussable if upcoming ones will be even sensefully usable in this project)
  - Latest releaes could bring performance enhancements (this I see as a great plus, because potentially we would like to visualize hundreds of paths, right?)
  - All the modules are available as packages via `npm` (maybe the D3 is then even more easily integrable into your software?)

So my personal taste would be to upgrade it (I may be able to lend you a hand here). But if you see no pressing reason then let us just close this thread ;)

**Comment by wolfib** [comment]
Thanks for presenting the pros and cons. I agree that it would be nice to have everything updated to v4. But I just don't have the time to do that atm (as I'm starting at a new job tomorrow).

Let's keep this open anyway and maybe revisit at a later point in time. If the performance of v4 allows bigger graphs to be drawn, this could be a big plus making the upgrade necessary.

**Comment by wolfib** [comment]
fixed. using d3 version 5.
