### ISSUE TITLE
Make the help dialog look like the track settings dialog

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#267]
Now the track settings dialog has a nice shadow and close button, but the help dialog doesn't. They should be consistent and maybe use a common slightly-customized-dialog component.

**Comment by rmccrear** [comment]
Do you think a CSS class on the CardBody inside the dialog would be enough? Or would a full component be better?

**Comment by adamnovak** [comment]
We could make there be a CSS class we use for all the dialogs, and just make sure to put the right markup in all of them to use it and have the close button. Or we could make a component that is like the basis of all our dialogs and has the right markup for a close button and to get the CSS for a shadow.

We've now added an info dialog when you click on reads, so I think we want to make sure that that looks the same too.

**Comment by adamnovak** [comment]
@rmccrear Please let us know if you want to do this one; I think @shreyasun might start on it soon if you don't.
