### ISSUE TITLE
Changing colors while the tube map is loading crashes the web page

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#269]
If you hit "go" to load a view, and while the view is loading you try to change the color settings ofr a track, the tube map web page crashes and React stops rendering the application.

I got a log like this:
```
HANDLING GO BUTTON: [HeaderForm.js:392](http://127.0.0.1:3001/Users/anovak/workspace/sequenceTubeMap/src/components/HeaderForm.js)
Rendering header form with graphSelectOptions:  
Array(15) [ "none", "COLO829_chr2_81963482-81964482.vg", "COLO829_chr2_81963482-81964482.vg.xg", "backward.vg", "backward.vg.xg", "cactus.hg", "cactus.pg", "cactus.vg", "cactus.vg.xg", "cactustest.vg", … ]
[HeaderForm.js:567](http://127.0.0.1:3001/Users/anovak/workspace/sequenceTubeMap/src/components/HeaderForm.js)
Rendering header form with graphSelectOptions:  
Array(15) [ "none", "COLO829_chr2_81963482-81964482.vg", "COLO829_chr2_81963482-81964482.vg.xg", "backward.vg", "backward.vg.xg", "cactus.hg", "cactus.pg", "cactus.vg", "cactus.vg.xg", "cactustest.vg", … ]
[HeaderForm.js:567](http://127.0.0.1:3001/Users/anovak/workspace/sequenceTubeMap/src/components/HeaderForm.js)
Uncaught TypeError: element is null
    generateNodeWidth tubemap.js:3667
    generateNodeWidth tubemap.js:3651
    createTubeMap tubemap.js:435
    setColorSet tubemap.js:347
    componentDidUpdate App.js:66
    React 6
    unstable_runWithPriority scheduler.development.js:468
    React 4
    unstable_runWithPriority scheduler.development.js:468
    React 10
    unstable_runWithPriority scheduler.development.js:468
    React 4
[tubemap.js:3667](http://127.0.0.1:3001/Users/anovak/workspace/sequenceTubeMap/src/util/tubemap.js)
The above error occurred in the <App> component:

App@http://127.0.0.1:3001/static/js/bundle.js:71:145
RenderedRoute@http://127.0.0.1:3001/static/js/bundle.js:121661:22
RenderedRoute@http://127.0.0.1:3001/static/js/bundle.js:121661:22
Routes@http://127.0.0.1:3001/static/js/bundle.js:122237:18
Router@http://127.0.0.1:3001/static/js/bundle.js:122167:24
BrowserRouter@http://127.0.0.1:3001/static/js/bundle.js:120370:18

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries. [react-dom.development.js:20085](http://127.0.0.1:3001/Users/anovak/workspace/sequenceTubeMap/node_modules/react-dom/cjs/react-dom.development.js)
Uncaught TypeError: element is null
    generateNodeWidth tubemap.js:3667
    generateNodeWidth tubemap.js:3651
    createTubeMap tubemap.js:435
    setColorSet tubemap.js:347
    componentDidUpdate App.js:66
    React 6
    unstable_runWithPriority scheduler.development.js:468
    React 4
    unstable_runWithPriority scheduler.development.js:468
    React 10
    unstable_runWithPriority scheduler.development.js:468
    React 4
[tubemap.js:3667](http://127.0.0.1:3001/Users/anovak/workspace/sequenceTubeMap/src/util/tubemap.js)
fetch canceled by componentWillUnmount The operation was aborted. [TubeMapContainer.js:33](http://127.0.0.1:3001/Users/anovak/workspace/sequenceTubeMap/src/components/TubeMapContainer.js)
```

**Comment by rmccrear** [comment]
The error seems to be occurring in the `componentDidUpdate` method of `App.js` (line 66). It’s trying to do `tubeMap.setColorSet()` for a track that hasn’t loaded yet. So, for example , wrapping it in a try/catch statement will suppress the error. Then, after loading is complete, `componentDidUpdate` will run again and load the new SVG. (Not very elegant, but it illustrates the problem.)

Another way would be to create a shared state called `isTrackLoading`, perhaps using Context. And use that to either disable the radio buttons while loading or having an `if(!isTrackLoading)` statement around `setColorSet()` etc., so it only runs if the track has loaded.

**Comment by adamnovak** [comment]
I think the real root of the problem is that `App.js` is talking directly to the `tubeMap` module, while the `TubeMapContainer` React component also thinks it is in charge of talking to the `tubeMap` module. If the `tubeMap` module is in a loading state where some methods are not allowed, `App.js` doesn't know it.

I think we should completely hide the `tubeMap` module behind the `TubeMapContainer` control. Then one control can be in charge of translating from React state to the imperative calls that the `tubeMap` module needs, and we won't be able to have this problem or any others like it.

**Comment by rmccrear** [comment]
That’s a good point. The piece of state at the center of this seems to be `visOptions`, in `App`. That could be passed down to `TubeMapContainer` as a prop.  So, `App` could keep `visOptions` as state, collect changes from `CustomizationAccordion`, then pass those changes down to `TubeMapContainer` to handle.
