### ISSUE TITLE
command line version

### ISSUE THREAD

**Issue by ekg** [vgteam/sequenceTubeMap#29]
I'm curious if we could have a version of this which would work on the command line, allowing us to pipe in the data and render out a (possibly static) visualization.

Also, the "oldindex" disappeared, https://vgteam.github.io/sequenceTubeMap/oldIndex.html. Is there any way to bring it back? It was very useful for rendering small graphs, much more legible than the `vg view -d - | dot` renderings.

**Comment by adamnovak** [comment]
I'm not sure what was at `oldIndex.html`, but probably #3 would solve what it was useful for.

This issue is I think a duplicate of #19.
