### ISSUE TITLE
Picking one single color doesn't work with graph tracks

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#301]
If you pick one color for a graph track, using the custom color picker, and you don't have a haplotype track, the first path from the graph track renders as the selected color, but the other paths render as black.

All the paths should render as the selected custom color.

@ducku Do you have any ideas as to why this might be happening?

**Comment by ducku** [comment]
@adamnovak Looks like there's a modulo edge case in generateTrackColor. I've made a commit in #293 to fix the issue.
