### ISSUE TITLE
Document when GFA node IDs can be used with `-n`

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#355]
If vg likes your GFA file, it won't change your node IDs. Then you can use your GFA node IDs with the region extraction scripts to highlight nodes.

We should document this, and document what needs to be true about your GFA file for the node IDs to come through.

We should also consider doing some translation of the `-n` values so that you can specify things in GFA space even if vg renumbers the nodes.

**Comment by adamnovak** [comment]
The GFA format: https://github.com/lh3/gfatools/blob/master/doc/rGFA.md#the-graph-alignment-format-gaf

**Comment by adamnovak** [comment]
Lancet seems to be spitting out GBZ files now though, so maybe the question the Lancet folks need answered is how to find their GFA nodes at the other end of the Giraffe pipeline.

But we should still answer this in the tube map docs.

**Comment by adamnovak** [comment]
At the vg meeting today we talked about sort of changing the project here to involve making a GFA and a GAF with string-named nodes, and seeing where that breaks the import scripts.

**Comment by ducku** [comment]
VG keeps node IDs the same when all node names are integers. However, node IDs are renamed upon the first encounter of a string-named node. Future nodes are renamed in order even if are integers. Renaming begins with the highest integer encounter so far + 1, or 1 if the node is the first node in the GFA file.

Here's an example of a rename in the order of the GFA file.

Original -> Renamed
3  ->  3
1  ->  1
five  ->  4
7  ->  5
four  ->  6

Renaming here began when "five" was encountered. It seems that some flag is enabled and all future node names are discarded in favor of +1 increments.

**Comment by ducku** [comment]
It seems that GAF files are not currently supported by the prepare_local_chunks script. 

The obvious problem I see is that the script renames the output to a .gam file, causing vg to crash. 
`GAM_CHUNK_NAME="${OUTDIR}/${GAM_LEADER}_0_${REGION_CONTIG}_${REGION_START}_${REGION_END}.gam"`

However, I'm unsure if other preparations need to be done to a GAF file. It also seems that some tubemap code needs to be changed to properly accept GAF files.
