### ISSUE TITLE
I want to learn more about your projects

### ISSUE THREAD

**Issue by Szhiha** [vgteam/sequenceTubeMap#372]
Would you mind telling me how to achieve generate a horizontal piece of base sequence like you? And most  importantly, how did you generate horizontal base sequences for these segments and nodes and correspond them one-to-one?  Thank you !

**Comment by Szhiha** [comment]
And I am wondering  what is 'from_length' and 'to_length' in your jsonfile

**Comment by adamnovak** [comment]
> Would you mind telling me how to achieve generate a horizontal piece of base sequence like you? And most importantly, how did you generate horizontal base sequences for these segments and nodes and correspond them one-to-one?

I'm not really sure what you mean here. I think we draw the horizontal pieces of sequence using normal SVG text in the SVG that we use to render the visualization. A lot of the logic to work out where to put the nodes in the visualization looks to be in [`generateNodeOrder()`](https://github.com/vgteam/sequenceTubeMap/blob/26266cc685f6492799d0426653df3d5e1bb5ff98/src/util/tubemap.js#L1439), but honestly the person who really understood the algorithm no longer works on the project.

We work out what the sequences should be and what nodes to make by using pangenomics tools to make graphs. Usually we would use [vg](https://github.com/vgteam/vg#vg) or [The Minigraph-Cactus Pangenome Pipeline](https://github.com/ComparativeGenomicsToolkit/cactus/blob/master/doc/pangenome.md) or [PanGenome Graph Builder](https://github.com/pangenome/pggb#readme).

> And I am wondering what is 'from_length' and 'to_length' in your jsonfile

`from_length` and `to_length` are from the vg data model: https://github.com/vgteam/libvgio/blob/45d8ada05ee1d1405ef44d93f2ac00a5a097dd09/deps/vg.proto#L51-L52

`from_length` is the number of bases of the graph node involved, and `to_length` is the number of bases of the aligned read that correspond to them. So if `from_length` is 0 and `to_length` is, say, 5, then you are looking at 5 bases inserted in the read that weren't present in the graph.

**Comment by Szhiha** [comment]
Thank you very much!

**Comment by adamnovak** [comment]
If that helps, I'm going to go ahead and close this issue. Thanks!
