### ISSUE TITLE
Problems accessing the server created with the command "npm run serve"

### ISSUE THREAD

**Issue by syresbr** [vgteam/sequenceTubeMap#394]
I want to run the sequenceTubeMap with my data and using the command it shows this on the terminal 
![image](https://github.com/vgteam/sequenceTubeMap/assets/46944679/5f420dc6-e27b-4382-b3a0-a1da21cde1d5)
and when I try to open no mozilla it shows this: 
![image](https://github.com/vgteam/sequenceTubeMap/assets/46944679/c21feccc-d345-4821-bb50-661c0ae49279)
And following the page I tried use the door 3001 but it shows this:
![image](https://github.com/vgteam/sequenceTubeMap/assets/46944679/4835d270-cc74-4128-b418-c39fe88eb65e)
What can be causing it?

**Comment by adamnovak** [comment]
@syresbr I think this will happen if you do `npm run serve` without having done `npm run build` first. The server is looking for the built files for the front-end to serve, but it can't find them, so you get a "Cannot GET /" error.

Try running `npm run build` first; that should solve your problem.

**Comment by syresbr** [comment]
It worked, thanks.

But another thing, the files that are being produced by the script to `prepare_vg.sh` are more than 5mb and the program isn't accepting when I tried to upload, is there a way to upload? 

The file I'm trying to upload is 402mb. The vg file that I used to generate was 319mb

**Comment by adamnovak** [comment]
If your file is large, you can put it in the `exampleData` folder in your copy of the tube map, instead of uploading it through the browser. It should then show up in the dropdowns when you go to pick a file.
