### ISSUE TITLE
US: .gam/.vg upload

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#4]
As a VG developer, I can upload a small raw .gam file and a small .vg graph, and have them be displayed together, so that I can see if they do what I want on a display that's more robust and intuitive than the GraphViz display.

**Comment by wolfib** [comment]
This requires calls to `vg index` and `vg chunk` to arrive at a json-version of the graph which can then be handled by tubeMaps. Do you consider it important that these steps are performed on the server? As an alternative I'm imagining a docker container which contains vg and scripts to perform the necessary transformations.

**Comment by adamnovak** [comment]
If the graph is small enough, and doesn't need chunking, you *might* be
able to get away with doing Protobuf decoding in Javascript, client side.

**Comment by adamnovak** [comment]
We have file upload support.
