### ISSUE TITLE
prepare scripts aren't executable

### ISSUE THREAD

**Issue by glennhickey** [vgteam/sequenceTubeMap#60]
The examples in the README like `docker exec -it <container_id> ./prepare_vg.sh <vg_file>` don't work because the scripts aren't runnable.
```
docker exec -it 50346e057492 ls -la | grep prepare
-rw-r--r--    1 root     root           207 Nov 19  2017 prepare_gam.sh
-rw-r--r--    1 root     root           270 Nov 19  2017 prepare_vg.sh
```
This is worked around by adding `sh` to the command.   `docker exec -it <container_id> sh ./prepare_vg.sh <vg_file>`

Either the README or the scripts should be updated to patch this...

**Comment by wolfib** [comment]
fixed (and reorganized - but the updated scripts are executable now)
