### ISSUE TITLE
Make data preprocessing scripts match current vg indexing API

### ISSUE THREAD

**Issue by jeizenga** [vgteam/sequenceTubeMap#62]
It seems like the work to make TubeMap use @adamnovak's fancy new indexing code is incomplete. I'm trying to work with the `file-upload` branch, which has the command line arguments fixed in `vg chunk`. However, the data preprocessing scripts (data/prepare.sh, data/prepare_dev.sh, backend/prepare_gam.sh, maybe more) still seem to be written to create the old RocksDB-based index. I understand that this branch is a work in progress, but I also can't use `master`, since it's still written for the old `vg chunk` API. 

@adamnovak says he can update the scripts for me, since he understands what's going on in the TubeMap internals.

**Comment by wolfib** [comment]
This should be fixed with commit 90491641ada3a3df14c9ff30e9e1fd83f249d229. Additionally, the file-upload branch has been merged into master. 

Let me know if you still encounter these problems.

**Comment by jeizenga** [comment]
I think it worked!
