### ISSUE TITLE
TubeMap requires both RocksDB and .gai index

### ISSUE THREAD

**Issue by jeizenga** [vgteam/sequenceTubeMap#63]
My understanding is that a `.sorted.gam` + `.gai` are supposed to provide all of the functionality of a `.gam.index`, but the software seems to be written to require both indexes. Is there a reason for this? If we could get rid of the RocksDB index, it could substantially reduce the preprocessing time.

**Comment by wolfib** [comment]
I believe that the `vg chunk` call in its current form requires all those files to be available.

@adamnovak or @glennhickey probably know more about this.

**Comment by adamnovak** [comment]
I thought I set it up so you only need the sorted GAM:

https://github.com/vgteam/vg/blob/d088ed914bc4dd51444e9aebcee326dcdb288038/test/t/30_vg_chunk.t#L33

Does it not work in your invocation?

**Comment by wolfib** [comment]
I was mistaken. I thought I had tried calling `vg chunk` without an existing RocksDB index and receiving an error message. This is not the case, so the RocksDB index is not needed anymore.

I removed it in commit e947d83d6fdb51ff14a95acfd521d8c157276ee0.
