### ISSUE TITLE
Build of docker container fails

### ISSUE THREAD

**Issue by eldariont** [vgteam/sequenceTubeMap#66]
Hi,
I tried to build the docker container (Docker for Mac) from the repo as described in the README but it failed:

```
>git clone https://github.com/vgteam/sequenceTubeMap.git
...
>cd sequencetubemap
>docker --version                                                                                                                                                                                  
Docker version 18.06.1-ce, build e68fc7a
>docker build -t wolfib/sequencetubemap:vg2018 .
Sending build context to Docker daemon  36.82MB
Step 1/32 : FROM quay.io/vgteam/vg:v1.6.0-382-g0fe63b96-t133-run as vgBinary
 ---> fc7c07520dfc
Step 2/32 : RUN mkdir -p /vg/data/out
 ---> Using cache
 ---> 807dfa1a2729
Step 3/32 : COPY data/ /vg/data
 ---> Using cache
 ---> 2daab09744e1
Step 4/32 : WORKDIR /vg/data
 ---> Using cache
 ---> 664951ff27b9
Step 5/32 : RUN ./prepare.sh
 ---> Running in ff712a2035c8
Generating xg and gbwt indices from vg files
cactus.vg:
snp1kg-BRCA1.vg:
x.vg:
Generating indices from gam files
NA12878-BRCA1.gam:
0
in the loop
writing
out the loop
The command '/bin/sh -c ./prepare.sh' returned a non-zero code: 1
```

Any ideas?

Cheers
David

**Comment by adamnovak** [comment]
It looks like the Dockerfile is trying to build with an old version of vg, which doesn't support the new sorted-GAM indexes that the tube map uses now.

https://github.com/vgteam/sequenceTubeMap/blob/301c521dfa18fb7a1c962baf8d68b569938678d7/Dockerfile#L4

It should probably be changed to use the last release, `v1.11.0-0-gea4aaded-t241-run `.

**Comment by wolfib** [comment]
I am working on an alternative way of installing and building tubeMaps, which does not rely on docker but instead simply uses 'npm install'. I have it mostly working (in the 'deployment'-branch), but it's not documented yet.
I hope to have it in a useful state after the weekend. Would that help?

**Comment by eldariont** [comment]
Thanks, I tried to replace the vg container with the most recent one but the build still fails in a later step. The npm way of installing sounds great. I will wait until it's ready and try it out then.

**Comment by wolfib** [comment]
The repo has been updated and the new (docker-free) installation procedure is described in the readme. It's basically `npm install` and `npm build`.

It would be great if you could let me know about your experience with the installation process. I hope it's a lot easier now, let me know if you encounter any problems or if anything is unclear. Thanks!

**Comment by eldariont** [comment]
Thanks Wolfgang! I was able to install sequenceTubeMap using the new installation procedure without any problems. It runs very smoothly now 👍 If there are no objections, I will close this thread.
