### ISSUE TITLE
Deselecting "Show sequence reads" breaks IVG completely

### ISSUE THREAD

**Issue by subwaystation** [vgteam/sequenceTubeMap#78]
When I deselect "Show sequence reads" IVG just shows a blank page.

The problem is that function [getPopUpText](https://github.com/vgteam/sequenceTubeMap/blob/441422467e60ce19f24c5dc4439b7df8e88a5324/src/util/tubemap.js#L2855) expects each node object to have instances of:

`incomingReads`
`internalReads`
`outgoingReads`

These instances are not created, when the user deselects the corresponding checkbox. Therefore, all synthetic examples and all other examples with the checkbox not ticked do not work.

I was very surprised to see `vg "small" example` working (with the checkbox ticked), because there is no corresponding `GAM` file in the example folder. I suspect that somehow the `GAM` from the initial request might be still "flying" around in SeqTubeMap or another one is used?

Anyhow, assuming the node pop up should view the current number of displayed reads I would propose the following fix [extending the code from line 380 on in tubemap.js](https://github.com/vgteam/sequenceTubeMap/blob/441422467e60ce19f24c5dc4439b7df8e88a5324/src/util/tubemap.js#L380):

```
  if (reads && config.showReads) {
    generateReadOnlyNodeAttributes();
    reverseReversedReads();
    generateTrackIndexSequences(reads);
    placeReads();
    tracks = tracks.concat(reads);
    // we do not have any reads to display
  } else {
    nodes.forEach(node => {
      node.incomingReads = [];
      node.outgoingReads = [];
      node.internalReads = [];
    });
  }
```

**Comment by wolfib** [comment]
Thank you! Sorry for taking so long to merge.
