### ISSUE TITLE
US: Common difference identification

### ISSUE THREAD

**Issue by adamnovak** [vgteam/sequenceTubeMap#8]
As a genomicist, I can see when several reads differ from the graph in the same way, so that I can evaluate the correctness of a variant call at that position.

**Comment by glennhickey** [comment]
Yeah, it would be handy to see differences in the reads that are not in the graph.  This is a hard problem in general, but for SNPs it shouldn't be too bad.  A SNP Edit in the GAM would look like

     {"to_length": 1, "from_length": 1, "sequence": "T"}

and in this case, the display should print a T at the appropriate position on the read.  Presumably small inserts could be done in a similar manner by printing the sequence (or maybe insertion length).  They look like (no from_length or from_length 0):

     {"to_length": 2, "sequence": "T"}

Deletes seem much harder as you would have to display a new edge to the graph.  Deletion edits have the to_length field set to 0

     {"from_length": 2}

**Comment by adamnovak** [comment]
That might work.

**Comment by adamnovak** [comment]
We don't do anything special for this, but I don't think we really need to. Seeing several mismatches/indels at the same position is enough.
