### ISSUE TITLE
confusion with genomic positions (coordinate axis) of minus strand genes

### ISSUE THREAD

**Issue by LilithElina** [vgteam/sequenceTubeMap#88]
I'm analysing a bacterial mini pangenome with five published strains and installed IVG to be able to visualise the graph. Some of the strains have a major inversion of about half of the genome compared to others, so genes are on the plus strand in some genomes and on the minus in others. In IVG I can enter a genome position from my selected reference strain and see e.g. the start of a gene of interest and then scroll to the right to see the gene sequence - if it is on the plus strand this makes perfect sense.

If the gene is located on the minus strand, I can enter the nucleotide position of the start of the gene and the right region will be displayed. Due to the orientation of the graph, I can again scroll right to follow the gene sequence, **but** the nucleotide positions shown on the axis will increase. This is confusing, since the official genomic position of the end of the gene is smaller than the position of the start, and I can use this smaller number to find the end of the gene in the graph.

Example: the annotation is "1043983 - 1045314 (- strand)". If I search for position 1045314 I find the start of the gene, and then I scroll to the right, e.g. to 1045320 to follow the gene. If I want to jump to the end of the gene without scrolling, I have to enter 1043983, though.

I have an example with pictures [here](https://cpang.netlify.app/post/day-3-bacterial-pangenomics/#visualisation-with-ivg).

**Comment by adamnovak** [comment]
The way the ruler appears to work is that is is only displayed when you describe the region you want to look at using a position along a named path. In that case, the ruler shows positions along that path. So if you ask for the lowest nucleotide position on a gene, the ruler is supposed to count up along that path.

I'm not entirely sure that we're interacting correctly here with the local-forward orientation of the nodes, when the paths visit them in reverse. I'll work on some test cases.

**Comment by adamnovak** [comment]
OK, I've managed to replicate this with a handmade example graph. It always lays out the nodes in their local forward orientations, and when a path goes in reverse through the graph layout, the ruler counts up from 0 at the highest path coordinate to whatever value it reaches at the lowest path coordinate displayed.

**Comment by adamnovak** [comment]
@LilithElina This should work now, although we won't have the online demo updated for a while yet.

**Comment by LilithElina** [comment]
Thank you!
