### ISSUE TITLE
update needed for compatible with xg version 15 or higher

### ISSUE THREAD

**Issue by XuewenWangUGA** [vgteam/sequenceTubeMap#99]
The current sequenceTubeMap is only working for xg version 14. However the vg index .xg is updated to version 15. The  sequenceTubeMap is not accepting the new version. Could you please update the  sequenceTubeMap  so it is compatibile with the vg graph index?

My tested xg index is from vg 1.27 index

Error:
terminate called after throwing an instance of 'xg::XGFormatError' what(): XG index file version 15 is too new to interpret (max version = 14) ERROR: Signal 6 occurred. VG has crashed. Run 'vg bugs --new' to report a bug. Stack trace path: /tmp/vg_crash_CYGjZN/stacktrace.txt Please include the stack trace file in your bug report!

**Comment by adamnovak** [comment]
This can track the update-current-files part of #104.
